### ISSUE TITLE
怎么没有教程中提到的 添加API功能?

### ISSUE THREAD

**Issue by ichat001** [MetaGLM/glm-cookbook#15]
### Feature request  / 功能建议

没有教程中提到的 添加API功能
https://github.com/MetaGLM/glm-cookbook/blob/main/glms/glms_custom_api_plugin.md

### Motivation / 动机

没有找到选项

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
实名认证

**Comment by ichat001** [comment]
> 实名认证

感谢回复, 我在体验中心实名认证过了, 发现还要在清言中再认证一次, 建议打通一下, 不再二次认证
另外, 没认证的用户也能看到 **添加API** 这个按钮, 点击的时候给个提醒去认证, 这样就友好多了

**Comment by zRzRzRzRzRzRzR** [comment]
收到，已经反馈清言部门
