### ISSUE TITLE
能不能使用自定义的API功能?

### ISSUE THREAD

**Issue by ichat001** [MetaGLM/glm-cookbook#16]
### Feature request  / 功能建议

看到下面链接的文章的标题写到: **插入自己的 API** 
https://github.com/MetaGLM/glm-cookbook/blob/main/glms/glms_custom_api_plugin.md

但结尾的常见问题中又如下写到:
**什么API都可以接入吗？
A： 需要通过我们的白名单系统的API才能接入，同时，发布带有第三方API功能的智能体需要通过我们的审核。**

那既然这样, 还叫插入自己的API吗? 
如果不能插入自己定义的API, 那我怎样实现和自己单位内部的软件API进行交互? 

我尝试一个简单的自己内部网址的get请求, 但就是无法测试成功, 也不报错, 而且还提示成功, 但实际后台并没有收到响应!

所以, 现在晕了, 到底能不能调用自己的API?

建议:
已实名认证的用户, 当选择发布为私密(如下图)的智能体时, 可以调用并测试自己的API, 或自己单位内部的API, 方便测试或调试之用
![simi](https://github.com/MetaGLM/glm-cookbook/assets/166457982/181de4f9-e60a-4cec-bc4a-200f62febd1c)

### Motivation / 动机

改进建议

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
能发布成功就行，相关问题已经记录

**Comment by ichat001** [comment]
> 能发布成功就行，相关问题已经记录

经多次尝试,还是没有成功调用自己单位内部的API, 
建议: 
如果不支持, 最好识别一下URL, 看它是否在咱们认证的API列表中, 如果没有那就直接红字提示: **非认证的API, 暂不支持**
不过这里调试, 确实要比在python代码中更加简单易懂一些, 
对于已实名,且不公开的智能体, 支持其内部API使用, 感觉也没有什么, 最重要的是, 在没有购买咱们的API之前, 可以拿这个智能体当样板, 让单位的同事都体验一下效果, 效果好, 有定制要求, 那肯定就付费买API了

**Comment by zRzRzRzRzRzRzR** [comment]
好，收到请求
