### ISSUE TITLE
在自定义的智能体中添加生成 python代码功能

### ISSUE THREAD

**Issue by ichat001** [MetaGLM/glm-cookbook#17]
### Feature request  / 功能建议

如果我测试自己的智能体很满意, 且我想购买API实现相同的功能时, 我还要写Python代码, 
能否在其中添加一个按钮, 点击后可自动生成该智能体的API调用的python代码, 这应该很简单, 因为该智能体, 肯定是后台的代码驱动的!
这样的话, 我只须在购买API后, 在代码中加上API的token就行了, 这样应该门槛就更低了

### Motivation / 动机

功能建议

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
就是智谱清言的智能体是吗？
智谱清言和API部门现在是隔离的，没有互通，这个可以考虑加入

**Comment by ichat001** [comment]
> 就是智谱清言的智能体是吗？ 智谱清言和API部门现在是隔离的，没有互通，这个可以考虑加入

对, 就是自定义的智能体, 
在体验中心就有这个功能, 可以直接看代码(如下图), 如果智能体要有这个功能, 那对爱好者和开发者都更加友好了, 
![aaaa](https://github.com/MetaGLM/glm-cookbook/assets/166457982/9f079011-c490-45fa-b61a-09c824353782)

**Comment by zRzRzRzRzRzRzR** [comment]
智能体和API开发是分开的，这是两个产品线，可以问问
