### ISSUE TITLE
glm怎么进行多轮连续对话？

### ISSUE THREAD

**Issue by znzjugod** [MetaGLM/glm-cookbook#22]
### System Info / 系統信息

Name: zhipuai
Version: 2.0.1

### Information / 问题信息

- [X] The official example scripts / 仓库中的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

none

### Expected behavior / 期待表现

在网页版中智谱清言中，可以在一个对话session里，提很多轮问题，并且模型能够保留历史对话记忆。
从prompt token的角度来说，应该存在api接口处理历史对话的token，网页版智谱清言是如何做到这一点的呢？
在用代码调用api时，
response = client.chat.completions.create(
    model="glm-4", # 填写需要调用的模型名称
    messages=messages,
    tools=tools,
    tool_choice="auto",
)
响应中存在以下关键字：
"id": "8231168139794583938",
  "model": "glm-4",
  "request_id": "8231168139794583938",
可否通过id管理多个对话的多轮对话？
即我创造了两个对话id，希望能通过某种方式，在每一个对话id里都进行多轮对话。
这种代码实现有cookbook吗？
感恩。

**Comment by zRzRzRzRzRzRzR** [comment]
message加入历史就行了，不能通过id连续对话，连续对话的本身是不断传越来越长的message，所以连续对话会越来约占用token
