### ISSUE TITLE
跑glm_infomation_extraction.ipynb的时候报错

### ISSUE THREAD

**Issue by mashagua** [MetaGLM/glm-cookbook#5]
### System Info / 系統信息

当代码跑到from langchain_community.chat_models import ChatZhipuAI

for question in question_prompt:
    messages = chat_template.format_messages(resume=data)
    messages.append(
        HumanMessage(
            content=question
        )
    )
    llm = ChatZhipuAI(
        temperature=0.01,
        model="glm-4",
        max_tokens=8192,
        stream=False,
    )
    messages.append(
        AIMessage(
            content=llm(messages).content
        )
    )
    print(messages[-1].content)的时候，llm(message)会报TypeError: 'NoneType' object is not subscriptable，请问该怎么修改

### Information / 问题信息

- [ ] The official example scripts / 仓库中的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python 3.8,transformer=4.38.2

### Expected behavior / 期待表现

我希望能返回你们notebook里的结果

**Comment by zRzRzRzRzRzRzR** [comment]
这个是没有执行代码，你试试8192调到8000呢

**Comment by lvjiujin** [comment]
> 这个是没有执行代码，你试试8192调到8000呢

No, it still occurs the same problem, even I modify the argument `max_tokens`  to 7000, the same problem.

**Comment by lvjiujin** [comment]
> ### System Info / 系統信息
> 当代码跑到from langchain_community.chat_models import ChatZhipuAI
> 
> for question in question_prompt: messages = chat_template.format_messages(resume=data) messages.append( HumanMessage( content=question ) ) llm = ChatZhipuAI( temperature=0.01, model="glm-4", max_tokens=8192, stream=False, ) messages.append( AIMessage( content=llm(messages).content ) ) print(messages[-1].content)的时候，llm(message)会报TypeError: 'NoneType' object is not subscriptable，请问该怎么修改
> 
> ### Information / 问题信息
> * [ ]  The official example scripts / 仓库中的示例脚本
> * [ ]  My own modified scripts / 我自己修改的脚本和任务
> 
> ### Reproduction / 复现过程
> python 3.8,transformer=4.38.2
> 
> ### Expected behavior / 期待表现
> 我希望能返回你们notebook里的结果

I know the problem ,you must change the system_prompt variable message `<resume>
{resume}
</resume>`  the {resume} to the specific resume.

**Comment by mashagua** [comment]
我重新调了还是这个错误，/opt/conda/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The function `__call__` was deprecated in LangChain 0.1.7 and will be removed in 0.2.0. Use invoke instead.
  warn_deprecated(
TypeError: 'NoneType' object is not subscriptable

**Comment by hiwei93** [comment]
> 我重新调了还是这个错误，/opt/conda/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The function `__call__` was deprecated in LangChain 0.1.7 and will be removed in 0.2.0. Use invoke instead. warn_deprecated( TypeError: 'NoneType' object is not subscriptable

langchian 现在调用组件需要使用 invoke 方法，调用 llm 的时候使用 invoke 方法：`llm.invoke(message)`

**Comment by zRzRzRzRzRzRzR** [comment]
langchain 智谱的PR没有通过，因此需要手动修改langchain community源代码支持

**Comment by zRzRzRzRzRzRzR** [comment]
下一个版本，langchain将支持GLM-4， 可以直接使用
