### ISSUE TITLE
ImportError: cannot import name 'ZhipuAI' from 'zhipuai'

### ISSUE THREAD

**Issue by yongxingMa** [MetaGLM/glm-cookbook#7]
### System Info / 系統信息

zhipuai-2.0.1

### Information / 问题信息

- [X] The official example scripts / 仓库中的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

import os
from zhipuai import ZhipuAI
client = ZhipuAI()

### Expected behavior / 期待表现

import os
from zhipuai import ZhipuAI
client = ZhipuAI()

**Comment by zRzRzRzRzRzRzR** [comment]
嗯？检查一下你环境内的库和pydantic，一定要是2.0.1的zhipuai，估计是没有安装成功，还是0.1.x的

**Comment by heiheiheibj** [comment]
pip install zhipuai==2.0.1.20240429 -i https://pypi.tuna.tsinghua.edu.cn/simple zhipuai 就可以了
